version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres
  redis:
    image: redis:latest
  api:
    build:
      context: ./server
      dockerfile: dev.dockerfile
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres_password
      - PG_DATABASE=postgres
      - PG_PORT=5432
    depends_on:
      - redis
      - postgres
      - nginx
  client:
    build:
      context: ./client
      dockerfile: dev.dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
      - api
  worker:
    build:
      context: ./worker
      dockerfile: dev.dockerfile
    volumes:
      - /app/node_modules
      - ./worker:/app
    depends_on:
      - redis
  nginx:
    build:
      context: ./nginx
      dockerfile: dev.dockerfile
    restart: always
    ports:
      - 8080:80
